### ISSUE TITLE
Add a tweet button to README.md

### ISSUE THREAD

**Issue by robin-thomas** [robin-thomas/serverless-aws-secrets#17]
Add tweet button to the top of `README.md`

Can use a link like:

[![Tweet](https://img.shields.io/twitter/url/http/shields.io.svg?style=social)](https://twitter.com/intent/tweet?text=Replace%20your%20environment%20variables%20with%20AWS%20secrets&url=https://github.com/robin-thomas/serverless-aws-secrets&hashtags=serverless,plugin,typescript,javascript,developers)

**Comment by jaas666** [comment]
PR submitted: #31
